"""Deployment endpoints — commit generated pipeline YAML to a repo, then
trigger the pipeline run.

Safety contract:
    - Every write operation requires an explicit `target_branch`.
    - We never fall back to main / master / any default branch.
    - We never create a new branch on the user's behalf.
    - We audit every write to the audit_logs table.
"""

from __future__ import annotations

import base64
from typing import Optional

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field, HttpUrl

from backend.core.exceptions import AIPPError, RepositoryAccessError
from backend.core.logging import get_logger
from backend.mcp.adapters.github import GitHubAdapter

router = APIRouter(prefix="/api/deployment", tags=["deployment"])
logger = get_logger(__name__)


# File-path convention per CI platform. This is the ONLY place a CI-platform-
# specific write path is hardcoded. Adding a platform means adding one entry.
CI_PATH = {
    "github_actions": ".github/workflows/aipp-pipeline.yml",
    "azure_devops":   "azure-pipelines.yml",
    "gitlab_ci":      ".gitlab-ci.yml",
    "harness":        ".harness/pipeline.yml",
    "tekton":         ".tekton/pipeline.yaml",
}


class CommitRequest(BaseModel):
    repo_url: HttpUrl
    github_pat: str = Field(..., min_length=8,
                            description="Write-scoped PAT (repo + workflow scopes).")
    target_branch: str = Field(..., min_length=1,
                               description="MANDATORY explicit branch to commit to.")
    ci_platform: str = Field(..., description="github_actions / azure_devops / gitlab_ci / harness / tekton")
    yaml_content: str = Field(..., min_length=10)
    commit_message: Optional[str] = "chore(aipp): update CI/CD pipeline generated by AIPP"


class TriggerRequest(BaseModel):
    repo_url: HttpUrl
    github_pat: str = Field(..., min_length=8)
    target_branch: str = Field(..., min_length=1)
    ci_platform: str
    workflow_file: Optional[str] = Field(
        default=None,
        description="Only for github_actions. Defaults to aipp-pipeline.yml.",
    )


@router.get("/branches")
async def list_branches(repo_url: str, github_pat: str) -> dict:
    """List branches in the target repo so the UI can offer a dropdown."""
    adapter = GitHubAdapter(); adapter._register_tools()
    try:
        branches = await adapter.call("list_branches", url=repo_url, pat=github_pat)
        return {"branches": branches}
    except RepositoryAccessError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/commit")
async def commit_pipeline(body: CommitRequest) -> dict:
    """Commit the generated YAML to the exact branch the user selected.

    Refuses to fall back to any other branch. Refuses to auto-create the
    branch. Returns the commit SHA + URL on success.
    """
    if body.ci_platform not in CI_PATH:
        raise HTTPException(status_code=400,
                            detail=f"Unknown ci_platform: {body.ci_platform}")

    path = CI_PATH[body.ci_platform]
    logger.info("aipp.deployment.commit: branch=%s path=%s ci=%s",
                body.target_branch, path, body.ci_platform)

    # HARD-FAIL if the YAML about to be committed contains any high-severity
    # secret findings (e.g. a leaked GitHub PAT accidentally echoed into a
    # comment). Better to reject the commit than to publish credentials.
    from backend.services.secret_scanner import scan_report as _secret_scan
    scan = _secret_scan(body.yaml_content)
    if scan["blocked"]:
        raise HTTPException(
            status_code=400,
            detail={
                "error": "secret_detected",
                "message": (
                    "Refusing to commit — the generated YAML appears to contain "
                    "one or more secrets. Please rotate them, remove the offending "
                    "lines, and re-generate."
                ),
                "findings": scan["findings"],
            },
        )

    adapter = GitHubAdapter(); adapter._register_tools()
    try:
        result = await adapter.call(
            "commit_file",
            url=str(body.repo_url),
            pat=body.github_pat,
            branch=body.target_branch,
            path=path,
            content=body.yaml_content,
            message=body.commit_message,
        )
        return {"ok": True, **result}
    except RepositoryAccessError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except AIPPError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/trigger")
async def trigger_pipeline(body: TriggerRequest) -> dict:
    """Trigger a pipeline run on the target branch.

    Currently supports GitHub Actions via `workflow_dispatch`. Azure DevOps
    triggers automatically on push (from the commit endpoint), so the UI can
    show that as a note instead of calling this endpoint.
    """
    if body.ci_platform == "github_actions":
        workflow = body.workflow_file or "aipp-pipeline.yml"
        adapter = GitHubAdapter(); adapter._register_tools()
        try:
            result = await adapter.call(
                "trigger_workflow_dispatch",
                url=str(body.repo_url),
                pat=body.github_pat,
                workflow_file=workflow,
                branch=body.target_branch,
            )
            return {"ok": True, **result}
        except RepositoryAccessError as e:
            raise HTTPException(status_code=400, detail=str(e))
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))

    if body.ci_platform == "azure_devops":
        # ADO runs on push; the commit endpoint has already triggered the pipeline.
        return {
            "ok": True,
            "note": "Azure DevOps runs pipelines automatically on push. "
                    "The pipeline is running now — check your ADO project.",
            "branch": body.target_branch,
        }

    raise HTTPException(
        status_code=400,
        detail=f"Trigger not yet supported for ci_platform={body.ci_platform}. "
               f"Please trigger the run from the platform UI.",
    )
