apiVersion: v1
kind: Secret
metadata:
  name: aipp-secret
  namespace: aipp
  labels:
    app.kubernetes.io/name: aipp-secret
    app.kubernetes.io/part-of: aipp-platform
type: Opaque
stringData:
  POSTGRES_USER: "aipp"
  POSTGRES_PASSWORD: "aipp_local_k8s_password"
  POSTGRES_DB: "aipp"
  POSTGRES_URL: "postgresql+asyncpg://aipp:aipp_local_k8s_password@aipp-postgres.aipp.svc.cluster.local:5432/aipp"
  POSTGRES_SYNC_URL: "postgresql+psycopg2://aipp:aipp_local_k8s_password@aipp-postgres.aipp.svc.cluster.local:5432/aipp"
  DATABASE_URL: "postgresql+asyncpg://aipp:aipp_local_k8s_password@aipp-postgres.aipp.svc.cluster.local:5432/aipp"

  JWT_SECRET: "2f63a53cc7171b41bc5ff3614d5ad0b9e78a382faf05e4f81487c190ba354f83d29901ca6dbf5b5f5dd48933c3da27e8250ebeff069986eae47711398b088222"
  AIPP_DEFAULT_ADMIN_EMAIL: "admin@dccloud.in.net"
  AIPP_DEFAULT_ADMIN_PASSWORD: "ipshom@21"
  AIPP_FERNET_KEY: "0dCBy1OTW_hmStw5rLXredNgSIiVHC5gTp42DP457sg="

  AIPP_LLM_KEY: "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"
  OPENAI_API_KEY: "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"
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: ""

  N8N_BASE_URL: "https://n8n.dccloud.in.net"
  N8N_API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YTViMGVhNi1iYjk1LTQ0N2ItYWQ2Ny00NjVhNGY4NGVjZDgiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiNzgzMzMyY2ItZjE2Ni00NzY0LWI2NzQtMTgwMjIyMGFmMDA4IiwiaWF0IjoxNzg5NTQzNDU0LCJleHAiOjE3OTcyNzMwMDB9.H4yQYHYmW8qZwBNUuYGe7SjAf16zxJyOmptjd60JgGw"

  PROXY_API_KEY: "AMS2zaOxP9t4aMgsn0IcMsKjOx3EkcvEOrIC_H61SXvD4gborHjoH4pJjieedloP"

  K8S_API_URL: "https://192.168.88.24:6443"
  K8S_TOKEN: "eyJhbGciOiJSUzI1NiIsImtpZCI6IkQtYzBOeTIybzE4b0lIeWtTQWJ3TXZvNDN4dzdXSFJJVENXLU1lZkpiaXMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxODE4NjgyNDUzLCJpYXQiOjE3ODcxNDY0NTMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYjU5ZjhhOGUtZGVlYy00MTNhLTg5YjEtZmZkYmI1NmQ5YmJlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6Im44bi1yZWFkZXIiLCJ1aWQiOiIxZTg4ZDRjZi1mMTExLTQ1N2UtOGY1MS0wNzc1YWUxMWIwNmUifX0sIm5iZiI6MTc4NzE0NjQ1Mywic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6bjhuLXJlYWRlciJ9.GJ8xvOkODVGMKsYO7nGjkhf0m0E3vlFI6vlHvVt1K-eA7VpO4hd-vn3VFyZXg6FYUcSRvAe1-2DvWa-3Y-Ln4eEwY2emgNSBC6Fy7EPeC97pmCsFaiHTL6uE96w_efSURShnwG0prJ59xPYi-1Zresy1zBtnoimisaEPyoqoZPlJPiDnZj4bikb0ExYIiJySlhNab9LHArh5zIqrBSAb5wxF2n1Anl1N8MVEU3N0EtYKmNFIQNJw4xmWyYZXZx40Yg9hoOXpXWKLVMdDus59YUzaOdecWONZjO4qos-bn0PUyHkQWC97Rn7JRgeq55J9sroSCU3AnTttscgjPMxH3A"
  K8S_CA_VERIFY: "false"

  PROXMOX_URL: "https://bharat.dccloud.in.net:8006"
  PROXMOX_TOKEN: "root@pam!n8n=22667abe-80e9-4809-88f2-d2e1300ba519"
  PROXMOX_NODE: "pve2"
  PROXMOX_VERIFY_SSL: "false"

  GRAFANA_URL: "https://grafana.dccloud.in.net"
  GRAFANA_API_KEY: "glsa_doJgcfn1OZgicxGKXsj7x7m2yT2r0er6_a1d9ef6e"

  GITHUB_PAT: "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"
  GH_ORG: "Subinoy2024"
  GH_REPO: "AIPP-AI-Driven-Pipeline-Platform-RACE"
  IAC_REPO_OWNER: "Subinoy2024"
  IAC_REPO_NAME: "AIPP-AI-Driven-Pipeline-Platform-RACE"
  GH_REPO_ALLOWLIST: "Subinoy2024/AIPP-AI-Driven-Pipeline-Platform-RACE"

  ADO_ORG: "https://dev.azure.com/DC-CLOUD-SERVICE/"
  ADO_PROJECT: "DC-CLOUD-SERVICE"
  ADO_PAT: "6GlOb6sDxPlfBEDzS9dn2Tmy6P2d4Cgf85r4UJqPRcuiG4q8eJy7JQQJ99CHACAAAAAwnooLAAASAZDO2kUK"

  AZURE_SUBSCRIPTION_ID: "3d88343d-13f8-4ac6-9b35-44e30ba1e895"
  AZURE_TENANT_ID: "474565c1-bca4-4295-a2f5-b0c7dbf2591c"
  AZURE_CLIENT_ID: "187f188e-af23-4090-ba72-820b22d4b87a"
  AZURE_CLIENT_SECRET: "3GT8Q~2wKnv~keJbmOSvMDEp7eMS2RcehpTeab7_"
